name: Build and push Unity to hub

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  buildForAllSupportedPlatforms:
    permissions:
      contents: read
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - WebGL # WebGL.
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          lfs: true

      - name: Caching Unity Library
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: integrations/Unity/simulate-unity/Library
          key: Library-Simulate
          restore-keys: |
            Library-Simulate-
            Library-

      - name: Build Unity Simulate
        uses: game-ci/unity-builder@eb1b9fba120c6e62c9fb7a7a81d6c107ce004c45  # v6.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: integrations/Unity/simulate-unity
          buildsPath: integrations/Unity/builds

      - name: Compress
        run: |
          mkdir ${{ github.workspace }}/compressed_builds
          cd ${{ github.workspace }}/integrations/Unity/builds/
          tar -cvzf ${{ github.workspace }}/compressed_builds/${{ matrix.targetPlatform }}.tar.gz ./${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: ${{ github.workspace }}/compressed_builds/${{ matrix.targetPlatform }}.tar.gz

  # buildForAllSupportedPlatforms:
  #   name: Simple build and push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
  #       with:
  #         fetch-depth: 0
  #         lfs: true

  #     - name: Compress
  #       run: |
  #         mkdir ${{ github.workspace }}/builds
  #         cd ${{ github.workspace }}/integrations/Godot/
  #         tar -cvzf ${{ github.workspace }}/builds/Standalone.tar.gz ./simulate_godot


  #     - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
  #       with:
  #         name: Build-Standalone
  #         path: ./builds/Standalone.tar.gz

  PushToHub:
    permissions: {}
    name: Upload if release
    needs: [buildForAllSupportedPlatforms]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          # name: artifact
          path: builds

      - name: Push builds to Hub
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          HF_TOKEN: ${{ secrets.UNITY_BUILD_PUSH }}
          HF_USERNAME: thomwolf
          REPO_NAME: unity_test
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/spaces/simulate-tests/$REPO_NAME
          cd ./$REPO_NAME
          rm -r ./builds
          mv ../builds .
          git config user.name thomwolf
          git config user.email thomas@huggingface.co
          git add .
          git commit -m "Build github commit ${{ github.event.pull_request.head.sha }}"
          git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/simulate-tests/$REPO_NAME main

      # git commit -m "${{github.event.release.tag_name}}"
