name: Delete dev documentation

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@9fc8a41d7729c424fdb2192f2f85ff63102ec9a3  # main
    with:
      pr_number: ${{ github.event.number }}
      package: simulate