name: Run simple loading test

on: [pull_request]

env:
  HF_HOME: ~/hf_cache

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      # see discussion at https://github.com/pyvista/pyvista/issues/2867
      matrix:
        include:
          - python-version: '3.8'
            vtk-version: '9.0.3'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: ~/.cache/pip
          key: Python-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.vtk-version }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements_test.txt') }}
          restore-keys: |
            Python-${{ runner.os }}-${{ matrix.python-version }}

      - name: Install the library
        run: |
          pip install --upgrade pip
          pip install .

      - name: Set up vtk
        if: ${{ matrix.vtk-version != 'latest' }}
        run: pip install vtk==${{ matrix.vtk-version }}

      - name: Run Simple loading test
        run: |
          python -c "import simulate as sm; scene = sm.Scene() + sm.Box()"
